apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: user-functions

resources:
  - serviceaccount.yaml
  - rbac.yaml
  - cronjob.yaml
  - init-job.yaml

# labels 제거 - Job/CronJob selector는 immutable
# labels:
#   - includeSelectors: false
#     pairs:
#       app.kubernetes.io/part-of: knative-faas-platform
