apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecr-refresher-role
  namespace: user-functions
  labels:
    app: ecr-token-refresher
    app.kubernetes.io/name: ecr-token-refresher
    app.kubernetes.io/part-of: knative-faas-platform
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["delete", "create", "patch", "get"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecr-refresher-binding
  namespace: user-functions
  labels:
    app: ecr-token-refresher
    app.kubernetes.io/name: ecr-token-refresher
    app.kubernetes.io/part-of: knative-faas-platform
subjects:
  - kind: ServiceAccount
    name: ecr-refresher
    namespace: user-functions
roleRef:
  kind: Role
  name: ecr-refresher-role
  apiGroup: rbac.authorization.k8s.io
