apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-refresher
  namespace: user-functions
  labels:
    app: ecr-token-refresher
    app.kubernetes.io/name: ecr-token-refresher
    app.kubernetes.io/part-of: knative-faas-platform
