apiVersion: apps/v1
kind: Deployment
metadata:
  name: polling-agent
  namespace: user-functions
  labels:
    app: polling-agent
    app.kubernetes.io/name: polling-agent
    app.kubernetes.io/part-of: knative-faas-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polling-agent
  template:
    metadata:
      labels:
        app: polling-agent
    spec:
      serviceAccountName: polling-agent
      containers:
        - name: polling-agent
          image: 900253478827.dkr.ecr.ap-northeast-2.amazonaws.com/polling-agent:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: polling-agent-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
