apiVersion: v1
kind: ServiceAccount
metadata:
  name: polling-agent
  namespace: faas-system
  labels:
    app: polling-agent
    app.kubernetes.io/name: polling-agent
    app.kubernetes.io/part-of: knative-faas-platform
imagePullSecrets:
  - name: ecr-secret