apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/knative-serving
  - ../../base/kourier
  - ../../base/nginx-ingress
  - ../../base/namespaces
  - ../../base/polling-agent
  - ../../ingress

patches:
  - path: patches/polling-agent-configmap.yaml
    target:
      kind: ConfigMap
      name: polling-agent-config
      namespace: faas-system
  - path: patches/polling-agent-deployment.yaml
    target:
      kind: Deployment
      name: polling-agent
      namespace: faas-system

namespace: ""  # Leave empty to use namespaces from resources
