apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - applications/knative-serving.yaml
  - applications/kourier.yaml
  - applications/nginx-ingress.yaml
  - applications/namespaces.yaml
  - applications/polling-agent.yaml
  - applications/ingress.yaml
  - applications/app-of-apps.yaml
