apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-faas-platform
  namespace: argocd
  labels:
    app.kubernetes.io/name: app-of-apps
    app.kubernetes.io/part-of: knative-faas-platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:Softbank-Hackathon-2025-Team-Green/manifest.git
    targetRevision: HEAD
    path: argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
