apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kourier
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: knative-faas-platform
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: git@github.com:Softbank-Hackathon-2025-Team-Green/manifest.git
    targetRevision: HEAD
    path: base/kourier
  destination:
    server: https://kubernetes.default.svc
    namespace: knative-serving
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
