apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Knative Serving CRDs only
# CRD는 core보다 먼저 설치되어야 함

resources:
  - https://github.com/knative/serving/releases/download/knative-v1.20.0/serving-crds.yaml

labels:
  - includeSelectors: false  # CRD에는 label을 추가하지 않음
    pairs:
      app.kubernetes.io/name: knative-crds
      app.kubernetes.io/part-of: knative-faas-platform
