apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: knative-serving

resources:
  # namespace.yaml 제거 - serving-core.yaml이 이미 namespace를 포함
  - https://github.com/knative/serving/releases/download/knative-v1.20.0/serving-crds.yaml
  - https://github.com/knative/serving/releases/download/knative-v1.20.0/serving-core.yaml

patches:
  - path: config-domain.yaml
    target:
      kind: ConfigMap
      name: config-domain

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: knative-faas-platform
